import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const buildDir = path.resolve("build");
const symLinkDir = path.resolve("../../../.obsidian/plugins/interactive-calendar-build");

// build시 생성되는 파일 build폴더에 복사
const copyBuildPlugin = {
	name: 'copy-build-plugin',
	setup(build) {
		build.onEnd(() => {
			try {
				if(!fs.existsSync(buildDir)){
					fs.mkdirSync(buildDir, { recursive: true });
				}
				if(fs.existsSync("manifest.json")){
					fs.copyFileSync("manifest.json", `${buildDir}/manifest.json`);
				}
				if(fs.existsSync("styles.css")){
					fs.copyFileSync("styles.css", `${buildDir}/styles.css`);
				}
				console.log("빌드 파일 복사 완료");

				// .obsidian/plugins에 폴더에 심볼릭 링크 폴더 생성
				if(!fs.existsSync(symLinkDir)){
					fs.symlinkSync(buildDir, symLinkDir, "dir");
					console.log("심볼릭 링크 폴더 생성 완료")
				}
			} catch(e) {
				console.log("빌드 파일 복사 실패", e);
			}
		})
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "build/main.js",
	plugins: [copyBuildPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
